/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.PeopleManager;

import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import model.Address;
import model.Person;
import model.PersonDirectory;
import java.util.regex.*;

/**
 *
 * @author Lenovo
 */
public class CreatePersonJPanel extends javax.swing.JPanel {

    JPanel userProcessContainer;
    PersonDirectory personDirectory;
    /**
     * Creates new form CreatePersonJPanel
     */
    public CreatePersonJPanel(JPanel container, PersonDirectory directory) {
        initComponents();
        
        userProcessContainer = container;
        personDirectory = directory;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnBack = new javax.swing.JButton();
        lblTitle = new javax.swing.JLabel();
        txtFirstName = new javax.swing.JTextField();
        lblFirstName = new javax.swing.JLabel();
        lblSSN = new javax.swing.JLabel();
        txtSSN = new javax.swing.JTextField();
        txtAge = new javax.swing.JTextField();
        lblAge = new javax.swing.JLabel();
        lblLastName = new javax.swing.JLabel();
        txtLastName = new javax.swing.JTextField();
        lblWorkAddress = new javax.swing.JLabel();
        lblHomeAddress = new javax.swing.JLabel();
        lblHACity = new javax.swing.JLabel();
        txtHACity = new javax.swing.JTextField();
        lblHAStreetAddress = new javax.swing.JLabel();
        lblHAUnitNumber = new javax.swing.JLabel();
        txtHAUnitNumber = new javax.swing.JTextField();
        txtHAStreetAddress = new javax.swing.JTextField();
        txtHAState = new javax.swing.JTextField();
        lblHAState = new javax.swing.JLabel();
        lblHAPhoneNumber = new javax.swing.JLabel();
        lblHAZipCode = new javax.swing.JLabel();
        txtHAZipCode = new javax.swing.JTextField();
        txtHAPhoneNumber = new javax.swing.JTextField();
        lblWAState = new javax.swing.JLabel();
        lblWAPhoneNumber = new javax.swing.JLabel();
        lblWAZipCode = new javax.swing.JLabel();
        txtWAZipCode = new javax.swing.JTextField();
        lblWACity = new javax.swing.JLabel();
        txtWAPhoneNumber = new javax.swing.JTextField();
        txtWACity = new javax.swing.JTextField();
        lblWAStreetAddress = new javax.swing.JLabel();
        lblWAUnitNumber = new javax.swing.JLabel();
        txtWAUnitNumber = new javax.swing.JTextField();
        txtWAStreetAddress = new javax.swing.JTextField();
        txtWAState = new javax.swing.JTextField();
        btnCreate = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 153));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnBack.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnBack.setForeground(new java.awt.Color(255, 102, 102));
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 12, -1, -1));

        lblTitle.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(255, 102, 102));
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("Create Profile");
        add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 78, 545, -1));
        add(txtFirstName, new org.netbeans.lib.awtextra.AbsoluteConstraints(197, 140, 114, -1));

        lblFirstName.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblFirstName.setForeground(new java.awt.Color(255, 102, 102));
        lblFirstName.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblFirstName.setText("First Name");
        add(lblFirstName, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 140, 68, -1));

        lblSSN.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblSSN.setForeground(new java.awt.Color(255, 102, 102));
        lblSSN.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblSSN.setText("SSN");
        add(lblSSN, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 168, 68, -1));
        add(txtSSN, new org.netbeans.lib.awtextra.AbsoluteConstraints(197, 168, 114, -1));
        add(txtAge, new org.netbeans.lib.awtextra.AbsoluteConstraints(531, 168, 114, -1));

        lblAge.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblAge.setForeground(new java.awt.Color(255, 102, 102));
        lblAge.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblAge.setText("Age");
        add(lblAge, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 168, 68, -1));

        lblLastName.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblLastName.setForeground(new java.awt.Color(255, 102, 102));
        lblLastName.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblLastName.setText("Last Name");
        add(lblLastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 140, 68, -1));
        add(txtLastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(531, 140, 114, -1));

        lblWorkAddress.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblWorkAddress.setForeground(new java.awt.Color(255, 102, 102));
        lblWorkAddress.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblWorkAddress.setText("Work Address");
        add(lblWorkAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 265, 124, -1));

        lblHomeAddress.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblHomeAddress.setForeground(new java.awt.Color(255, 102, 102));
        lblHomeAddress.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblHomeAddress.setText("Home Address");
        add(lblHomeAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 265, -1, -1));

        lblHACity.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblHACity.setForeground(new java.awt.Color(255, 102, 102));
        lblHACity.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblHACity.setText("City");
        add(lblHACity, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 360, 114, 22));

        txtHACity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHACityActionPerformed(evt);
            }
        });
        add(txtHACity, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 361, 114, -1));

        lblHAStreetAddress.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblHAStreetAddress.setForeground(new java.awt.Color(255, 102, 102));
        lblHAStreetAddress.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblHAStreetAddress.setText("Street Address");
        add(lblHAStreetAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 302, 114, 22));

        lblHAUnitNumber.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblHAUnitNumber.setForeground(new java.awt.Color(255, 102, 102));
        lblHAUnitNumber.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblHAUnitNumber.setText("House Number");
        add(lblHAUnitNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 331, 114, 22));
        add(txtHAUnitNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 332, 114, -1));
        add(txtHAStreetAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 303, 114, -1));
        add(txtHAState, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 390, 114, -1));

        lblHAState.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblHAState.setForeground(new java.awt.Color(255, 102, 102));
        lblHAState.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblHAState.setText("State");
        add(lblHAState, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 389, 114, 22));

        lblHAPhoneNumber.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblHAPhoneNumber.setForeground(new java.awt.Color(255, 102, 102));
        lblHAPhoneNumber.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblHAPhoneNumber.setText("Phone");
        add(lblHAPhoneNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 447, 114, 22));

        lblHAZipCode.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblHAZipCode.setForeground(new java.awt.Color(255, 102, 102));
        lblHAZipCode.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblHAZipCode.setText("Zip code");
        add(lblHAZipCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 418, 114, 22));
        add(txtHAZipCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 419, 114, -1));

        txtHAPhoneNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHAPhoneNumberActionPerformed(evt);
            }
        });
        add(txtHAPhoneNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 448, 114, -1));

        lblWAState.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblWAState.setForeground(new java.awt.Color(255, 102, 102));
        lblWAState.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblWAState.setText("State");
        add(lblWAState, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 386, 101, -1));

        lblWAPhoneNumber.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblWAPhoneNumber.setForeground(new java.awt.Color(255, 102, 102));
        lblWAPhoneNumber.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblWAPhoneNumber.setText("Phone");
        add(lblWAPhoneNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 442, 101, -1));

        lblWAZipCode.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblWAZipCode.setForeground(new java.awt.Color(255, 102, 102));
        lblWAZipCode.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblWAZipCode.setText("Zip code");
        add(lblWAZipCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 414, 101, -1));
        add(txtWAZipCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(531, 414, 114, -1));

        lblWACity.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblWACity.setForeground(new java.awt.Color(255, 102, 102));
        lblWACity.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblWACity.setText("City");
        add(lblWACity, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 358, 101, -1));
        add(txtWAPhoneNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(531, 442, 114, -1));
        add(txtWACity, new org.netbeans.lib.awtextra.AbsoluteConstraints(531, 358, 114, -1));

        lblWAStreetAddress.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblWAStreetAddress.setForeground(new java.awt.Color(255, 102, 102));
        lblWAStreetAddress.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblWAStreetAddress.setText("Street Address");
        add(lblWAStreetAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 302, 101, -1));

        lblWAUnitNumber.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblWAUnitNumber.setForeground(new java.awt.Color(255, 102, 102));
        lblWAUnitNumber.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblWAUnitNumber.setText("Unit Number");
        add(lblWAUnitNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 330, 101, -1));
        add(txtWAUnitNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(531, 330, 114, -1));
        add(txtWAStreetAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(531, 302, 114, -1));
        add(txtWAState, new org.netbeans.lib.awtextra.AbsoluteConstraints(531, 386, 114, -1));

        btnCreate.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnCreate.setForeground(new java.awt.Color(255, 102, 102));
        btnCreate.setText("Create Person");
        btnCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateActionPerformed(evt);
            }
        });
        add(btnCreate, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 496, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void txtHACityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHACityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHACityActionPerformed

    private void btnCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateActionPerformed
        // TODO add your handling code here:
        byte age;
        int SSN;
        
        String firstName = txtFirstName.getText();
        String lastName = txtLastName.getText();
        
        String HAStreetAddress = txtHAStreetAddress.getText();
        int HAUnitNumber;
        String HACity = txtHACity.getText();
        String HAState = txtHAState.getText();
        short HAZipCode;
        long HAPhoneNumber;
        
        String WAStreetAddress = txtWAStreetAddress.getText();
        int WAUnitNumber;
        String WACity = txtWACity.getText();
        String WAState = txtWAState.getText();
        short WAZipCode;
        long WAPhoneNumber;
        
        if (firstName.isBlank()|lastName.isBlank()|
            HAStreetAddress.isBlank()|HACity.isBlank()|HAState.isBlank()|
            WAStreetAddress.isBlank()|WACity.isBlank()|WAState.isBlank())
            {
            JOptionPane.showMessageDialog(this, "All fields are mandatory", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        try{
            age = Byte.parseByte(txtAge.getText());
            SSN = Integer.parseInt(txtSSN.getText());
            HAUnitNumber = Integer.parseInt(txtHAUnitNumber.getText());
            HAZipCode = Short.parseShort(txtHAZipCode.getText());
            HAPhoneNumber = Long.parseLong(txtHAPhoneNumber.getText());
            WAUnitNumber = Integer.parseInt(txtWAUnitNumber.getText());
            WAZipCode = Short.parseShort(txtWAZipCode.getText());
            WAPhoneNumber = Long.parseLong(txtWAPhoneNumber.getText());
        } catch (Exception e){
            JOptionPane.showMessageDialog(this, "All fields are mandatory in the correct format of numbers and Strings", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        
        //validations(age, SSN, firstName, lastName, HAStreetAddress, HAUnitNumber, HACity, HAState, HAZipCode, HAPhoneNumber, WAStreetAddress, WAUnitNumber, WACity, WAState, WAZipCode, WAPhoneNumber);
        
        int personAge = Integer.valueOf(age);
        if (4 > personAge || personAge > 121){
            JOptionPane.showMessageDialog(this, "Age should be between 5 and 120", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        String SSN_Str = Integer.toString(SSN);
        System.out.println(SSN_Str);
        if (SSN_Str.charAt(1) == '0'){
            JOptionPane.showMessageDialog(this, "SSN should not start with zero", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        String SSNRegex = "\\d{9}";
        String SSN_String = txtSSN.getText();
        Pattern pSSN = Pattern.compile(SSNRegex);
        Matcher mSSN = pSSN.matcher(SSN_String);
        
        if(!mSSN.matches()){
            JOptionPane.showMessageDialog(this, "SSN should be a 9 digit number", "Warning", JOptionPane.WARNING_MESSAGE);
            return; 
        }
        
        //String check = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789";
        for (int i=0 ; i < firstName.length(); i++){
            if (Character.isWhitespace(firstName.charAt(i))){
                JOptionPane.showMessageDialog(this, "FirstName cannot have space in it", "Warning", JOptionPane.WARNING_MESSAGE);
                return;
            }
        }
        
        for (int i=0 ; i < lastName.length(); i++){
            if (Character.isWhitespace(lastName.charAt(i))){
                JOptionPane.showMessageDialog(this, "LastName cannot have space in it", "Warning", JOptionPane.WARNING_MESSAGE);
                return;
            }
        }
        
        if (HAStreetAddress.length()<= 2 || HACity.length()<= 2 || HAState.length()<= 2 || WAStreetAddress.length()<= 2 || WACity.length()<= 2 || WAState.length()<= 2 ){
            JOptionPane.showMessageDialog(this, "Street Address, City and State should atleast have 2 characters", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        String unitNumRegex = "[0-9]+";
        String HAUnitNumber_Str = txtHAUnitNumber.getText();
        String WAUnitNumber_Str = txtWAUnitNumber.getText();
        Pattern pUnitNum = Pattern.compile(unitNumRegex);
        Matcher mHAUnitNum = pUnitNum.matcher(HAUnitNumber_Str);
        Matcher mWAUnitNum = pUnitNum.matcher(WAUnitNumber_Str);
        
        if(!mHAUnitNum.matches() || !mWAUnitNum.matches()){
            JOptionPane.showMessageDialog(this, "Unit numbers should only be digits", "Warning", JOptionPane.WARNING_MESSAGE);
            return; 
        }
        
        String zipCodeRegex = "\\d{5}";
        String HAZipCode_Str = txtHAZipCode.getText();
        String WAZipCode_Str = txtWAZipCode.getText();
        Pattern pZipCode = Pattern.compile(zipCodeRegex);
        Matcher mHAZip = pZipCode.matcher(HAZipCode_Str);
        Matcher mWAZip = pZipCode.matcher(WAZipCode_Str);
        
        if(!mHAZip.matches() || !mWAZip.matches()){
            JOptionPane.showMessageDialog(this, "Zip code should be a 5 digit number", "Warning", JOptionPane.WARNING_MESSAGE);
            return; 
        }
        
        String phoneNumRegex = "\\d{10}";
        String HAPhone_Str = txtHAPhoneNumber.getText();
        String WAPhone_Str = txtWAPhoneNumber.getText();
        Pattern pPhone = Pattern.compile(phoneNumRegex);
        Matcher mHAPhone = pPhone.matcher(HAPhone_Str);
        Matcher mWAPhone = pPhone.matcher(WAPhone_Str);
        
        if(!mHAPhone.matches() || !mWAPhone.matches()){
            JOptionPane.showMessageDialog(this, "Phone number should be a 10 digit number", "Warning", JOptionPane.WARNING_MESSAGE);
            return; 
        }
        
        Person p = personDirectory.addPerson();
        
        p.setFirstName(firstName);
        p.setLastName(lastName);
        p.setAge(age);
        p.setSSN(SSN);
              
        Address homeAddress = new Address(HAStreetAddress, HAUnitNumber, HACity, HAState, HAZipCode, HAPhoneNumber);
        Address workAddress = new Address(WAStreetAddress, WAUnitNumber, WACity, WAState, WAZipCode, WAPhoneNumber);
        
        p.setHomeAddress(homeAddress);
        p.setWorkAddress(workAddress);
        
        JOptionPane.showMessageDialog(this, "Person Profile created successfully", "Information", JOptionPane.INFORMATION_MESSAGE);
        
        txtFirstName.setText("");
        txtLastName.setText("");
        txtAge.setText("");
        txtSSN.setText("");
        
        txtHAStreetAddress.setText("");
        txtHAUnitNumber.setText("");
        txtHACity.setText("");
        txtHAState.setText("");
        txtHAZipCode.setText("");
        txtHAPhoneNumber.setText("");
        
        txtWAStreetAddress.setText("");
        txtWAUnitNumber.setText("");
        txtWACity.setText("");
        txtWAState.setText("");
        txtWAZipCode.setText("");
        txtWAPhoneNumber.setText("");
        
    }//GEN-LAST:event_btnCreateActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    private void txtHAPhoneNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHAPhoneNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHAPhoneNumberActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnCreate;
    private javax.swing.JLabel lblAge;
    private javax.swing.JLabel lblFirstName;
    private javax.swing.JLabel lblHACity;
    private javax.swing.JLabel lblHAPhoneNumber;
    private javax.swing.JLabel lblHAState;
    private javax.swing.JLabel lblHAStreetAddress;
    private javax.swing.JLabel lblHAUnitNumber;
    private javax.swing.JLabel lblHAZipCode;
    private javax.swing.JLabel lblHomeAddress;
    private javax.swing.JLabel lblLastName;
    private javax.swing.JLabel lblSSN;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblWACity;
    private javax.swing.JLabel lblWAPhoneNumber;
    private javax.swing.JLabel lblWAState;
    private javax.swing.JLabel lblWAStreetAddress;
    private javax.swing.JLabel lblWAUnitNumber;
    private javax.swing.JLabel lblWAZipCode;
    private javax.swing.JLabel lblWorkAddress;
    private javax.swing.JTextField txtAge;
    private javax.swing.JTextField txtFirstName;
    private javax.swing.JTextField txtHACity;
    private javax.swing.JTextField txtHAPhoneNumber;
    private javax.swing.JTextField txtHAState;
    private javax.swing.JTextField txtHAStreetAddress;
    private javax.swing.JTextField txtHAUnitNumber;
    private javax.swing.JTextField txtHAZipCode;
    private javax.swing.JTextField txtLastName;
    private javax.swing.JTextField txtSSN;
    private javax.swing.JTextField txtWACity;
    private javax.swing.JTextField txtWAPhoneNumber;
    private javax.swing.JTextField txtWAState;
    private javax.swing.JTextField txtWAStreetAddress;
    private javax.swing.JTextField txtWAUnitNumber;
    private javax.swing.JTextField txtWAZipCode;
    // End of variables declaration//GEN-END:variables

}
